### ISSUE TITLE
cannot convert to tflite

### ISSUE THREAD

**Issue by ofirkris** [hhj1897/face_parsing#5]
Hello, thanks for sharing this great study.
I'm researching face parsing and  i'm trying to port to Tflite and compare the performance, but I can't since this is using special ops - it uses "**grid sample**" 

What do you suggest I can do in order to test on Tflite/CoreML?

Will training on Lapa dataset improve the accuracy? if not why?

**Comment by yiminglin-ai** [comment]
Sorry I don't know about tflite/coreml. Training on Lapa helps when faces are not in large poses.
